### ISSUE TITLE
Extended cogwheels breaks create recipes

### ISSUE THREAD

**Issue by gittibene** [Rabbitminers/Extended-Cogs#45]
Precision Mechanisms are uncraftable with Extended Cogwheels installed. Pleease fix this!

Fabric 1.19.2

**Comment by TearinGaming786** [comment]
another user on a similar thread but for the entire fabric create mod figured out the issue, if anyone working on the mod is reading this, they pointed out "the tag c:nuggets/iron, following Forge convention, instead of the Fabric convention c:iron_nuggets." and the same issue is found with c:gold_plate also being incorrectly formatted for the forge version still. they mentioned a data pack could fix this. figured id mention it here since they posted these solutions on the issue page for create mod itself instead of the specific addon mod causing the issue. fair warning, i have no idea what im talking abt and am paraphrasing the words of another, ill link the post this was all said too. 
https://github.com/Fabricators-of-Create/Create/issues/651

**Comment by SteveNichols5** [comment]
This will fix the precision mechanism, its a datapack so just do the datapack thing.

[precision_mechanism_fix_5.zip](https://github.com/Rabbitminers/Extended-Cogwheels/files/11715695/precision_mechanism_fix_5.zip)
