### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by LIUKRAST** [Rabbitminers/Extended-Cogs#61]
Since the GitHub repo is already updated to create 0.5.1 I was wondering how do you build the project and export the jar. **I will only do this for private purpose**. I'm using Intellij IDEA as IDE but when trying to run the build task it exports a jar which does not work (even though the runClient task works)

**Comment by xXNightsecretXx** [comment]
I don't see a 0.5.1 branch

**Comment by LIUKRAST** [comment]
> I don't see a 0.5.1 branch

https://github.com/Rabbitminers/Extended-Cogwheels/blob/multiloader-1.18.2/build.gradle

The create version is 0.5.1 here

**Comment by Muvkina** [comment]
Take the build from the subproject for forge this would be forge/build/libs/extendgears-*.jar or fabric/build/libs/extendedgears-*.jar at least when building on cli with gradle. Not the developer just was letting you know though :) (but yeah don't ask for support for this version since obviously in development) (although the dev may be ok with that generally it seems most devs don't like that but i can't speak for them)

**Comment by Rabbitminers** [comment]
You can download betas from our discord server or from releases here on github. Between that the mod is unstable and shouldn't be used
