### ISSUE TITLE
Cog material types not existing

### ISSUE THREAD

**Issue by BonesharkTV** [Rabbitminers/Extended-Cogs#84]
Bug description:
The cogs that should be added(spruce, jungle, copper and other materials)dont show up in the creative menu, neither are they craftable.

Expected behavior:
I expected that there would be more options for cogs material wise.

![grafik](https://github.com/Rabbitminers/Extended-Cogwheels/assets/136222164/a4e6d859-c8e6-44c6-bf2e-3fc95a07f1e1)

Version and modloader:
 - Forge 40.2.17
 - 1.18.2

Modlist:
![grafik](https://github.com/Rabbitminers/Extended-Cogwheels/assets/136222164/a35bb3da-893c-442b-bd45-572ddd8287b2)

**Comment by FangFury** [comment]
The different textured cog variants are not added as individual items, you hold the material you wish to re-texture them as (i.e. wood plank, metal ingot) and right click on a placed cog in order to alter the appearance, similar to how encasing items with the different casing blocks works. Is this method of texturing the different cogs working, or is it entirely nonfunctional?

**Comment by BonesharkTV** [comment]
works know, thanks for the help

**Comment by BonesharkTV** [comment]
Works now, thanks for the Help
